{{- if .Values.conversationHub.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todea.conversationHub.name" . }}
  labels:
    {{- include "todea.labels" . | nindent 4 }}
    app.kubernetes.io/component: conversation-hub
spec:
  type: {{ .Values.conversationHub.service.type }}
  ports:
    - port: {{ .Values.conversationHub.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "todea.conversationHub.selectorLabels" . | nindent 4 }}
{{- end }}
